CC		= /usr/lib/mingw64-toolchain/bin/x86_64-w64-mingw32-gcc
SDL2_CONFIG	= ../../../mingw/src/SDL2-2.30.6/x86_64-w64-mingw32/bin/sdl2-config
BINDIR          = ../target/win-x64
OBJDIR          = $(BINDIR)/objects

include ../mk/base.mk
