= Der Clou! - SDL Port v2.8

A burglary simulation game.

Original version by:

* neo Software Produktions GmbH

SDL port by:

* Vasco Alexandre da Silva Costa <vasco.costa AT gmail.com>
** Original SDL 2 port

* Thomas Trummer <cosp AT antaresdesign.org>
** HSC music code and valuable insights

* Vladimir Vrzić <vvrzic AT gmail.com>
** Resizable game window, configurable texture filtering, configurable font shadows, cross-compiler windows build, and other fixes and improvements

* Jens Granseuer <jensgr AT gmx.net>
** patches

* Patrick Fehr
** bug reports

* Felix Schwarz
** bug reports


Please read the LICENSE file in this directory before proceeding.


== Building

You need SDL 2.0 installed. Type `make` to compile.


== Running

Run `derclou` to start the game.

Here is the command line usage:

....
Syntax:
        derclou [-h] [-d[<num>]] [-f] [-g<num>] [-q<filter>] [-a] [-m<num>] [-s<num>] [-t]
Flags:
        -h         - show help
        -d[<num>]  - enable debug output (debug level [1])
        -f         - run in full screen mode
        -g<num>    - graphics scale factor
        -q<filter> - scaler quality (nearest,linear)
        -a         - enable font shadows
        -m<num>    - music volume (0-255)
        -s<num>    - sfx volume (0-255)
        -t         - trainer
....


== Implementation

The game autodetects the following data files:

  a. Der Clou!
  b. Der Clou! CD-ROM
  c. Der Clou! Profidisk
  d. Der Clou! Profidisk CD-ROM

PC version only.

It also autodetects the language: German/English/French/Spanish/Slovak.

The game tries to load the datafiles from the directory pointed by
  the environment variable `DERCLOU_ROOTDIR`.
  Failing that it will try to load them from the current directory.

The free datafiles (German) can no longer be downloaded from the neo website.
  The website has been down for some time. I put these files in a tarball here:
  https://sites.google.com/site/vascocosta/theclue

Just `cd` into the created directory and run `derclou` to play.

The English datafiles have not been released by neo Software since they
  do not own the copyright for them. Not that you should have much trouble
  finding them.


== Request

If you like this software please contact neo Software Produktions GmbH and help
me persuade them to re-release the source code under an actual open source
license like the GNU GPL. Be nice to them.

Enjoy!

== Links

https://en.wikipedia.org/wiki/The_Clue!
http://www.mobygames.com/game/clue
